{{- if .Values.secretEnv.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-backend.secretName" . }}
  labels:
    {{- include "generic-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secretEnv.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end -}}
